version: '3'

services:
  ocsapplication:
    build: ./
    image: ocsinventory-server-ssl:2.8
    container_name : ocsinventory-server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs/:/etc/ocs-certs/
      - "perlcomdata:/etc/ocsinventory-server"
      - "ocsreportsdata:/usr/share/ocsinventory-reports/ocsreports"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/httpd/conf.d"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
      # SSL certificate
      OCS_SSL_KEY: /etc/ocs-certs/server.key
      OCS_SSL_CERT: /etc/ocs-certs/server.cert
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb    

  ocsdb :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    command: --max-allowed-packet 10485760
    ports :
      - 3306:3306
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    networks:
      - localocs
  
networks:
  localocs:

volumes:
  perlcomdata:
  ocsreportsdata:
  varlibdata:
  httpdconfdata:
  sqldata:
  
